server:
  port: 9991

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
       defaultZone: http://user:123456@www.modaolc.com:8761/eureka/

logging:
  level: info
  file: ${spring.application.name}-${server.port}.log

