server:
  port: 8083

spring:
  application:
    name: zuul


eureka:
  client:
    service-url:
       defaultZone: http://user:123456@www.modaolc.com:8761/eureka/


logging:
  level: info


zuul:
  routes:
     api-a-url:
           path: /api/a/**
           serviceId: consumer
    api-b-url:
           path: /api/b/**
           serviceId: consumer

##禁用过滤器（zuul.过滤器className.filterType.disable=true）
zuul:
   PreRequestFilter:
     pre:
       disable: true

